.align 2
voicegroup196::
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115 @ Synth Bass 0
	voice_keysplit voicegroup006, KeySplitTable2 @ string ensemble 1
	voice_keysplit voicegroup007, KeySplitTable3 @ trumpet 2
	voice_keysplit voicegroup009, KeySplitTable5 @ French Horn 3
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 246, 0, 226 @ Timpani 4
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_84, 255, 247, 0, 221 @ Piano 5
	
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149 @ Fingered Bass 6
	voice_keysplit voicegroup008, KeySplitTable4 @ Tuba 7
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 255, 165 @ Flute 8
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 188 @ Fretless Bass 9
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 242 @ Glockenspiel 10
