.align 2
voicegroup195::
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_84, 255, 247, 0, 221 @ Piano
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 165, 90, 216 @Tubular Bells
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115 @ Synth Bass
	voice_square_2_alt 60, 0, 1, 0, 2, 6, 2 @ Sawtooth Synth
	voice_keysplit voicegroup009, KeySplitTable5 @ French Horn
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0 @ Square
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 128, 0, 255, 206
	voice_keysplit_all voicegroup002 @ Drums
