.align 2
voicegroup194::
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 242 @ Glockenspiel
	voice_keysplit_all voicegroup002 @ Drums
	voice_directsound 60, 0, violin, 255, 255, 0, 221 @ Violin
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 0, 255, 127 
	voice_keysplit voicegroup009, KeySplitTable5 @ French Horn
	voice_keysplit voicegroup006, KeySplitTable2 @ string ensemble
	voice_directsound 60, 0, violin, 255, 255, 0, 221 @ Violin
	voice_keysplit voicegroup009, KeySplitTable5 @ French Horn
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_72, 255, 250, 0, 221 @ Piano
