.align 2
voicegroup191::
	voice_keysplit_all voicegroup002
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 188
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 128, 0, 255, 206
	voice_keysplit voicegroup009, KeySplitTable5 @ french horn
	voice_keysplit voicegroup006, KeySplitTable2 @ string ensemble
	voice_keysplit voicegroup007, KeySplitTable3 @ trumpet
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 255, 165
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 7, 0  
	voice_square_2 60, 0, 0, 0, 0, 5, 0
