.align 2
voicegroup192::
	voice_keysplit_all voicegroup002
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115
	voice_keysplit voicegroup007, KeySplitTable3 @ trumpet
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 246, 0, 226
	voice_keysplit voicegroup009, KeySplitTable5 @ french horn
	voice_keysplit voicegroup006, KeySplitTable2 @ string ensemble
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_programmable_wave 60, 0, ProgrammableWaveData_86B4830, 0, 7, 15, 1
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 150, 255, 0, 221
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 255, 165
	voice_directsound 60, 0, clarinet60, 255, 255, 0, 221
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_72, 255, 250, 0, 221
