.align 2
voicegroup193::
	voice_keysplit_all voicegroup002
	voice_programmable_wave 60, 0, ProgrammableWaveData_86B49B0, 0, 7, 15, 1
	voice_keysplit voicegroup009, KeySplitTable5
	voice_keysplit voicegroup008, KeySplitTable4
	voice_keysplit voicegroup007, KeySplitTable3
	voice_directsound 60, 0, orchestrahit72, 200, 255, 255, 255
	voice_keysplit voicegroup006, KeySplitTable2
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 165, 154, 235
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 216
	voice_directsound 60, 0, violin, 255, 255, 0, 221
