#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_H

#define FRONTIER_CHALLENGE(facility, mode) ((facility << 8) + mode)

// Battle Frontier facility ids.
#define FRONTIER_FACILITY_TOWER    0
#define FRONTIER_FACILITY_DOME     1
#define FRONTIER_FACILITY_PALACE   2  // also Verdanturf Tent
#define FRONTIER_FACILITY_ARENA    3  // also Fallarbor Tent
#define FRONTIER_FACILITY_FACTORY  4  // also Slateport Tent
#define FRONTIER_FACILITY_PIKE     5
#define FRONTIER_FACILITY_PYRAMID  6
#define NUM_FRONTIER_FACILITIES    7
// VAR_FRONTIER_FACILITY is re-used for the below facilities as well
#define FACILITY_LINK_CONTEST      7
#define FACILITY_UNION_ROOM        8
#define FACILITY_MULTI_OR_EREADER  9  // Direct Corner multi battles, multi battle with Steven, and e-Reader battles

// Battle Frontier lvl modes.
#define FRONTIER_LVL_50   0
#define FRONTIER_LVL_OPEN 1
#define FRONTIER_LVL_TENT 2

// Battle Frontier battle modes.
#define FRONTIER_MODE_SINGLES      0
#define FRONTIER_MODE_DOUBLES      1
#define FRONTIER_MODE_MULTIS       2
#define FRONTIER_MODE_LINK_MULTIS  3
#define FRONTIER_MODE_COUNT        4

// Challenge Statuses
#define CHALLENGE_STATUS_SAVING   1
#define CHALLENGE_STATUS_PAUSED   2
#define CHALLENGE_STATUS_WON      3
#define CHALLENGE_STATUS_LOST     4

// Special trainer battles.
#define SPECIAL_BATTLE_TOWER 0
#define SPECIAL_BATTLE_SECRET_BASE 1
#define SPECIAL_BATTLE_EREADER 2
#define SPECIAL_BATTLE_DOME 3
#define SPECIAL_BATTLE_PALACE 4
#define SPECIAL_BATTLE_ARENA 5
#define SPECIAL_BATTLE_FACTORY 6
#define SPECIAL_BATTLE_PIKE_SINGLE 7
#define SPECIAL_BATTLE_STEVEN 8
#define SPECIAL_BATTLE_PIKE_DOUBLE 9
#define SPECIAL_BATTLE_PYRAMID 10
#define SPECIAL_BATTLE_MULTI 11
#define SPECIAL_BATTLE_FACTORY_FAKE 12

#define MAX_BATTLE_FRONTIER_POINTS 9999
#define MAX_STREAK 9999

// These sets of facility ids would be redunant if the order was consistent
// The order is important for this set so that all the non-link records can be continuous
#define RANKING_HALL_BATTLE_TOWER_SINGLES   0
#define RANKING_HALL_BATTLE_TOWER_DOUBLES   1
#define RANKING_HALL_BATTLE_TOWER_MULTIS    2
#define RANKING_HALL_BATTLE_DOME            3
#define RANKING_HALL_BATTLE_PALACE          4
#define RANKING_HALL_BATTLE_ARENA           5
#define RANKING_HALL_BATTLE_FACTORY         6
#define RANKING_HALL_BATTLE_PIKE            7
#define RANKING_HALL_BATTLE_PYRAMID         8
#define RANKING_HALL_BATTLE_TOWER_LINK      9

#define FRONTIER_MANIAC_BATTLE_TOWER_SINGLES   0
#define FRONTIER_MANIAC_BATTLE_TOWER_DOUBLES   1
#define FRONTIER_MANIAC_BATTLE_TOWER_MULTIS    2
#define FRONTIER_MANIAC_BATTLE_TOWER_LINK      3
#define FRONTIER_MANIAC_BATTLE_DOME            4
#define FRONTIER_MANIAC_BATTLE_FACTORY         5
#define FRONTIER_MANIAC_BATTLE_PALACE          6
#define FRONTIER_MANIAC_BATTLE_ARENA           7
#define FRONTIER_MANIAC_BATTLE_PIKE            8
#define FRONTIER_MANIAC_BATTLE_PYRAMID         9
#define FRONTIER_MANIAC_FACILITY_COUNT        10

#define FRONTIER_MANIAC_MESSAGE_COUNT 3

// Frontier Gambler
#define FRONTIER_GAMBLER_WAITING     0
#define FRONTIER_GAMBLER_PLACED_BET  1
#define FRONTIER_GAMBLER_WON         2
#define FRONTIER_GAMBLER_LOST        3

#define FRONTIER_GAMBLER_BET_5      0
#define FRONTIER_GAMBLER_BET_10     1
#define FRONTIER_GAMBLER_BET_15     2
#define FRONTIER_GAMBLER_BET_CANCEL 3

#define FRONTIER_GAMBLER_CHALLENGE_COUNT 12

#define EXCHANGE_CORNER_DECOR1_CLERK     0
#define EXCHANGE_CORNER_DECOR2_CLERK     1
#define EXCHANGE_CORNER_VITAMIN_CLERK    2
#define EXCHANGE_CORNER_HOLD_ITEM_CLERK  3

#define F_EV_SPREAD_HP         (1 << 0)
#define F_EV_SPREAD_ATTACK     (1 << 1)
#define F_EV_SPREAD_DEFENSE    (1 << 2)
#define F_EV_SPREAD_SPEED      (1 << 3)
#define F_EV_SPREAD_SP_ATTACK  (1 << 4)
#define F_EV_SPREAD_SP_DEFENSE (1 << 5)

#define BATTLE_FRONTIER_ITEM_NONE 0
#define BATTLE_FRONTIER_ITEM_HEALTH_WING 1
#define BATTLE_FRONTIER_ITEM_MUSCLE_WING 2
#define BATTLE_FRONTIER_ITEM_RESIST_WING 3
#define BATTLE_FRONTIER_ITEM_GENIUS_WING 4
#define BATTLE_FRONTIER_ITEM_CLEVER_WING 5
#define BATTLE_FRONTIER_ITEM_SWIFT_WING 6
#define BATTLE_FRONTIER_ITEM_PRETTY_WING 7
#define DUMMY                            8
#define BATTLE_FRONTIER_ITEM_CHERI_BERRY 9
#define BATTLE_FRONTIER_ITEM_CHESTO_BERRY 10
#define BATTLE_FRONTIER_ITEM_PECHA_BERRY 11
#define BATTLE_FRONTIER_ITEM_RAWST_BERRY 12
#define BATTLE_FRONTIER_ITEM_ASPEAR_BERRY 13
#define DUMMY2
#define BATTLE_FRONTIER_ITEM_LEPPA_BERRY 15
#define BATTLE_FRONTIER_ITEM_ORAN_BERRY 16
#define BATTLE_FRONTIER_ITEM_PERSIM_BERRY 17
#define BATTLE_FRONTIER_ITEM_LUM_BERRY 18
#define BATTLE_FRONTIER_ITEM_SITRUS_BERRY 19
#define BATTLE_FRONTIER_ITEM_FIGY_BERRY 20
#define BATTLE_FRONTIER_ITEM_WIKI_BERRY 21
#define BATTLE_FRONTIER_ITEM_MAGO_BERRY 22
#define BATTLE_FRONTIER_ITEM_AGUAV_BERRY 23
#define BATTLE_FRONTIER_ITEM_IAPAPA_BERRY 24
#define BATTLE_FRONTIER_ITEM_RAZZ_BERRY 25
#define BATTLE_FRONTIER_ITEM_BLUK_BERRY 26
#define BATTLE_FRONTIER_ITEM_NANAB_BERRY 27
#define BATTLE_FRONTIER_ITEM_WEPEAR_BERRY 28
#define BATTLE_FRONTIER_ITEM_PINAP_BERRY 29
#define BATTLE_FRONTIER_ITEM_POMEG_BERRY 30
#define BATTLE_FRONTIER_ITEM_KELPSY_BERRY 31
#define BATTLE_FRONTIER_ITEM_QUALOT_BERRY 32
#define BATTLE_FRONTIER_ITEM_HONDEW_BERRY 33
#define BATTLE_FRONTIER_ITEM_GREPA_BERRY 34
#define BATTLE_FRONTIER_ITEM_TAMATO_BERRY 35
#define BATTLE_FRONTIER_ITEM_CORNN_BERRY 36
#define BATTLE_FRONTIER_ITEM_MAGOST_BERRY 37
#define BATTLE_FRONTIER_ITEM_RABUTA_BERRY 38
#define BATTLE_FRONTIER_ITEM_NOMEL_BERRY 39
#define BATTLE_FRONTIER_ITEM_SPELON_BERRY 40
#define BATTLE_FRONTIER_ITEM_PAMTRE_BERRY 41
#define BATTLE_FRONTIER_ITEM_WATMEL_BERRY 42
#define BATTLE_FRONTIER_ITEM_DURIN_BERRY 43
#define BATTLE_FRONTIER_ITEM_BELUE_BERRY 44
#define BATTLE_FRONTIER_ITEM_OCCA_BERRY 45
#define BATTLE_FRONTIER_ITEM_PASSHO_BERRY 46
#define BATTLE_FRONTIER_ITEM_WACAN_BERRY 47
#define BATTLE_FRONTIER_ITEM_RINDO_BERRY 48
#define BATTLE_FRONTIER_ITEM_YACHE_BERRY 49
#define BATTLE_FRONTIER_ITEM_CHOPLE_BERRY 50
#define BATTLE_FRONTIER_ITEM_KEBIA_BERRY 51
#define BATTLE_FRONTIER_ITEM_SHUCA_BERRY 52
#define BATTLE_FRONTIER_ITEM_COBA_BERRY 53
#define BATTLE_FRONTIER_ITEM_PAYAPA_BERRY 54
#define BATTLE_FRONTIER_ITEM_TANGA_BERRY 55
#define BATTLE_FRONTIER_ITEM_CHARTI_BERRY 56
#define BATTLE_FRONTIER_ITEM_KASIB_BERRY 57
#define BATTLE_FRONTIER_ITEM_HABAN_BERRY 58
#define BATTLE_FRONTIER_ITEM_COLBUR_BERRY 59
#define BATTLE_FRONTIER_ITEM_BABIRI_BERRY 60
#define BATTLE_FRONTIER_ITEM_CHILAN_BERRY 61
#define BATTLE_FRONTIER_ITEM_ROSELI_BERRY 62
#define BATTLE_FRONTIER_ITEM_LIECHI_BERRY 63
#define BATTLE_FRONTIER_ITEM_GANLON_BERRY 64
#define BATTLE_FRONTIER_ITEM_SALAC_BERRY 65
#define BATTLE_FRONTIER_ITEM_PETAYA_BERRY 66
#define BATTLE_FRONTIER_ITEM_APICOT_BERRY 67
#define BATTLE_FRONTIER_ITEM_LANSAT_BERRY 68
#define BATTLE_FRONTIER_ITEM_STARF_BERRY 69
#define BATTLE_FRONTIER_ITEM_MICLE_BERRY 70
#define BATTLE_FRONTIER_ITEM_ENIGMA_BERRY 71
#define BATTLE_FRONTIER_ITEM_CUSTAP_BERRY 72
#define BATTLE_FRONTIER_ITEM_JABOCA_BERRY 73
#define BATTLE_FRONTIER_ITEM_ROWAP_BERRY 74
#define BATTLE_FRONTIER_ITEM_KEE_BERRY 75
#define BATTLE_FRONTIER_ITEM_MARANGA_BERRY 76
#define BATTLE_FRONTIER_ITEM_BRIGHT_POWDER 77
#define BATTLE_FRONTIER_ITEM_WHITE_HERB 78
#define BATTLE_FRONTIER_ITEM_QUICK_CLAW 79
#define BATTLE_FRONTIER_ITEM_MENTAL_HERB 80
#define BATTLE_FRONTIER_ITEM_CHOICE_BAND 81
#define BATTLE_FRONTIER_ITEM_KINGS_ROCK 82
#define BATTLE_FRONTIER_ITEM_SILVER_POWDER 83
#define BATTLE_FRONTIER_ITEM_SMOKE_BALL 84
#define BATTLE_FRONTIER_ITEM_FOCUS_BAND 85
#define BATTLE_FRONTIER_ITEM_SCOPE_LENS 86
#define BATTLE_FRONTIER_ITEM_METAL_COAT 87
#define BATTLE_FRONTIER_ITEM_LEFTOVERS 88
#define BATTLE_FRONTIER_ITEM_DUBIOUS_DISC 89
#define BATTLE_FRONTIER_ITEM_REAPER_CLOTH 90
#define BATTLE_FRONTIER_ITEM_RAZOR_CLAW 91
#define BATTLE_FRONTIER_ITEM_RAZOR_FANG 92
#define BATTLE_FRONTIER_ITEM_PRISM_SCALE 93
#define BATTLE_FRONTIER_ITEM_WHIPPED_DREAM 94
#define BATTLE_FRONTIER_ITEM_SACHET 95
#define BATTLE_FRONTIER_ITEM_SOFT_SAND 96
#define BATTLE_FRONTIER_ITEM_HARD_STONE 97
#define BATTLE_FRONTIER_ITEM_MIRACLE_SEED 98
#define BATTLE_FRONTIER_ITEM_BLACK_GLASSES 99
#define BATTLE_FRONTIER_ITEM_BLACK_BELT 100
#define BATTLE_FRONTIER_ITEM_SILK_SCARF 101
#define BATTLE_FRONTIER_ITEM_UP_GRADE 102
#define BATTLE_FRONTIER_ITEM_SHELL_BELL 103
#define BATTLE_FRONTIER_ITEM_CHOICE_SCARF 104
#define BATTLE_FRONTIER_ITEM_CHOICE_SPECS 105
#define BATTLE_FRONTIER_ITEM_FOCUS_SASH 106
#define BATTLE_FRONTIER_ITEM_WIDE_LENS 107
#define BATTLE_FRONTIER_ITEM_ZOOM_LENS 108
#define BATTLE_FRONTIER_ITEM_METRONOME 109
#define BATTLE_FRONTIER_ITEM_MUSCLE_BAND 110
#define BATTLE_FRONTIER_ITEM_WISE_GLASSES 111
#define BATTLE_FRONTIER_ITEM_EXPERT_BELT 112
#define BATTLE_FRONTIER_ITEM_LIGHT_CLAY 113
#define BATTLE_FRONTIER_ITEM_ICY_ROCK 114
#define BATTLE_FRONTIER_ITEM_SMOOTH_ROCK 115
#define BATTLE_FRONTIER_ITEM_HEAT_ROCK 116
#define BATTLE_FRONTIER_ITEM_DAMP_ROCK 117
#define BATTLE_FRONTIER_ITEM_DESTINY_KNOT 118
#define BATTLE_FRONTIER_ITEM_GRIP_CLAW 119
#define BATTLE_FRONTIER_ITEM_LIFE_ORB 120
#define BATTLE_FRONTIER_ITEM_TOXIC_ORB 121
#define BATTLE_FRONTIER_ITEM_FLAME_ORB 122
#define BATTLE_FRONTIER_ITEM_STICKY_BARB 123
#define BATTLE_FRONTIER_ITEM_BLACK_SLUDGE 124
#define BATTLE_FRONTIER_ITEM_IRON_BALL 125
#define BATTLE_FRONTIER_ITEM_LAGGING_TAIL 126
#define BATTLE_FRONTIER_ITEM_SHED_SHELL 127
#define BATTLE_FRONTIER_ITEM_BIG_ROOT 128
#define BATTLE_FRONTIER_ITEM_EVIOLITE 129
#define BATTLE_FRONTIER_ITEM_FLOAT_STONE 130
#define BATTLE_FRONTIER_ITEM_ROCKY_HELMET 131
#define BATTLE_FRONTIER_ITEM_AIR_BALLOON 132
#define BATTLE_FRONTIER_ITEM_RED_CARD 133
#define BATTLE_FRONTIER_ITEM_RING_TARGET 134
#define BATTLE_FRONTIER_ITEM_BINDING_BAND 135
#define BATTLE_FRONTIER_ITEM_EJECT_BUTTON 136
#define BATTLE_FRONTIER_ITEM_ABSORB_BULB 137
#define BATTLE_FRONTIER_ITEM_CELL_BATTERY 138
#define BATTLE_FRONTIER_ITEM_LUMINOUS_MOSS 139
#define BATTLE_FRONTIER_ITEM_SNOWBALL 140
#define BATTLE_FRONTIER_ITEM_WEAKNESS_POLICY 141
#define BATTLE_FRONTIER_ITEM_ASSAULT_VEST 142
#define BATTLE_FRONTIER_ITEM_SAFETY_GOGGLES 143
#define BATTLE_FRONTIER_ITEM_ADRENALINE_ORB 144
#define BATTLE_FRONTIER_ITEM_TERRAIN_EXTENDER 145
#define BATTLE_FRONTIER_ITEM_PROTECTIVE_PADS 146
#define BATTLE_FRONTIER_ITEM_ELECTRIC_SEED 147
#define BATTLE_FRONTIER_ITEM_PSYCHIC_SEED 148
#define BATTLE_FRONTIER_ITEM_MISTY_SEED 149
#define BATTLE_FRONTIER_ITEM_GRASSY_SEED 150
#define BATTLE_FRONTIER_ITEM_LAX_INCENSE 151
#define BATTLE_FRONTIER_ITEM_THICK_CLUB 152
#define BATTLE_FRONTIER_ITEM_ABOMASITE 153
#define BATTLE_FRONTIER_ITEM_ABSOLITE 154
#define BATTLE_FRONTIER_ITEM_AERODACTYLITE 155
#define BATTLE_FRONTIER_ITEM_AGGRONITE 156
#define BATTLE_FRONTIER_ITEM_ALAKAZITE 157
#define BATTLE_FRONTIER_ITEM_ALTARIANITE 158
#define BATTLE_FRONTIER_ITEM_AMPHAROSITE 159
#define BATTLE_FRONTIER_ITEM_AUDINITE 160
#define BATTLE_FRONTIER_ITEM_BANETTITE 161
#define BATTLE_FRONTIER_ITEM_BEEDRILLITE 162
#define BATTLE_FRONTIER_ITEM_BLASTOISINITE 163
#define BATTLE_FRONTIER_ITEM_BLAZIKENITE 164
#define BATTLE_FRONTIER_ITEM_CAMERUPTITE 165
#define BATTLE_FRONTIER_ITEM_CHARIZARDITE_X 166
#define BATTLE_FRONTIER_ITEM_CHARIZARDITE_Y 167
#define BATTLE_FRONTIER_ITEM_DIANCITE 168
#define BATTLE_FRONTIER_ITEM_GALLADITE 169
#define BATTLE_FRONTIER_ITEM_GARCHOMPITE 170
#define BATTLE_FRONTIER_ITEM_GARDEVOIRITE 171
#define BATTLE_FRONTIER_ITEM_GENGARITE 172
#define BATTLE_FRONTIER_ITEM_GLALITITE 173
#define BATTLE_FRONTIER_ITEM_GYARADOSITE 174
#define BATTLE_FRONTIER_ITEM_HERACRONITE 175
#define BATTLE_FRONTIER_ITEM_HOUNDOOMINITE 176
#define BATTLE_FRONTIER_ITEM_KANGASKHANITE 177
#define BATTLE_FRONTIER_ITEM_LATIASITE 178
#define BATTLE_FRONTIER_ITEM_LATIOSITE 179
#define BATTLE_FRONTIER_ITEM_LOPUNNITE 180
#define BATTLE_FRONTIER_ITEM_LUCARIONITE 181
#define BATTLE_FRONTIER_ITEM_MANECTITE 182
#define BATTLE_FRONTIER_ITEM_MAWILITE 183
#define BATTLE_FRONTIER_ITEM_MEDICHAMITE 184
#define BATTLE_FRONTIER_ITEM_METAGROSSITE 185
#define BATTLE_FRONTIER_ITEM_MEWTWONITE_X 186
#define BATTLE_FRONTIER_ITEM_MEWTWONITE_Y 187
#define BATTLE_FRONTIER_ITEM_PIDGEOTITE 188
#define BATTLE_FRONTIER_ITEM_PINSIRITE 189
#define BATTLE_FRONTIER_ITEM_SABLENITE 190
#define BATTLE_FRONTIER_ITEM_SALAMENCITE 191
#define BATTLE_FRONTIER_ITEM_SCEPTILITE 192
#define BATTLE_FRONTIER_ITEM_SCIZORITE 193
#define BATTLE_FRONTIER_ITEM_SHARPEDONITE 194
#define BATTLE_FRONTIER_ITEM_SLOWBRONITE 195
#define BATTLE_FRONTIER_ITEM_STEELIXITE 196
#define BATTLE_FRONTIER_ITEM_SWAMPERTITE 197
#define BATTLE_FRONTIER_ITEM_TYRANITARITE 198
#define BATTLE_FRONTIER_ITEM_VENUSAURITE 199
#define BATTLE_FRONTIER_ITEM_MAGNET 200
#define BATTLE_FRONTIER_ITEM_TWISTED_SPOON 201
#define BATTLE_FRONTIER_ITEM_POWER_HERB 202

#endif // GUARD_CONSTANTS_BATTLE_FRONTIER_H
