gText_Birch_Welcome:: @ 82C897B
	.string "Hi there!\n"
	.string "My name is Scott.\p"
	.string "I'm sure you already know that, though.\p"
	.string "This is definitely not\n"
	.string "your first Pokémon adventure.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "You were called here because of your\n"
	.string "familiarity with high-level Pokémon.\p"
	.string "You have an affinity for\n"
	.string "Pokémon with strength\l" 
	.string "like this Bisharp, right?\p"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "You have an affinity for\n"
	.string "Pokémon with strength\l" 
	.string "like this Bisharp, right?\p"
	.string "As such a trainer,\n"
	.string "you've earned the right to be here.\p"
	.string "In a few brief moments, the\n"
	.string "Battle Frontier will be at your disposal.\p"
	.string "Your job is to master\n"
	.string "its seven facilities.\p"
	.string "Anyway, I imagine you\n"
	.string "will be quite busy soon.\p"
	.string "Let's speed up this\n"
	.string "registration, shall we?\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "Let's get your style.$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Would you say you're Cool?\n"
	.string "Or are you maybe more Cute?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Splendid.\n"
	.string "Now, what's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Understood.\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Once you arrive,\n"
	.string "I'll be sure to greet you.\p"
	.string "Have a safe trip, {PLAYER}{KUN}!\p"
	.string "$"
